baseURL = "https://pzane123.github.io/"
defaultContentLanguage = "zh"
enableEmoji = true
enableRobotsTXT = true
languageCode = "zh-cn"
# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"
theme = "gokarna"
title = "Fugo‘s Blog"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/images/page_picture.jpg"

  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css" integrity="sha384-5TcZemv2l/9On385z///+d7MSYlvIEw9FuZTIdZ14vJLqWphw7e7ZPuOiCHJcFCP" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js" integrity="sha384-cMkvdD8LoxVzGF/RPUKAcvmm49FQ0oxwDF3BGKtDXcEc+T1b2N+teh/OJfpU0jr6" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js" integrity="sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          throwOnError : false
        });
      });
    </script>
  """

  description = "记录技术与生活"
  footer = "Powered by Hugo • Theme: Gokarna"
  metaKeywords = ["blog", "gokarna", "hugo"]
  showBackToTopButton = true

  socialIcons = [
    {name = "email", url = "mailto:1974183730@qq.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Search"
    pre = "<span data-feather='search'></span>"
    url = "/search/"
    weight = 5

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 6

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true
